name: Discord Notifications

on:
  push:
  issues:
    types: [opened, closed, reopened]
  pull_request:
    types: [opened, closed, reopened]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
  release:
    types: [published]
  watch:
    types: [started]

jobs:
  notify:
    uses: Generacja-Innowacja/github-webhook-bot/.github/workflows/reusable-bot.yml@main
    secrets:
      DISCORD_REPORTING_BOT_WEBHOOK: ${{ secrets.DISCORD_REPORTING_BOT_WEBHOOK }}